contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true
baseurl=""
title="Dark Simplicity"
author="administrator"
languageCode = "en-us"
min_version = 0.14

[taxonomies]
  tag = "tags"

[params]
  #description = ""
  #copyright=""
  #google_analytics_id=""
  #disqus_shortname=""
