author = "Matt Rhone"
name = "darksimplicity"
description = "A Dark Minimalist Theme for Hugo utilizing the Lost Grid Framework."
license = "MIT"
source_repo = "http://github.com/kritoke/darksimplicity"
tags = ["blog", "personal", "dark", "minimalist"]
